project:
  type: website
  output-dir: _site

execute:
  freeze: true

website:
  title: "Capital Aikikai of Wisconsin"
  favicon: assets/images/favicon.png
  page-navigation: true

  navbar:
    title: "Capital Aikikai<br>of Wisconsin"
    logo: "assets/images/caow-logo-transparent-bg.png"
    left:
      - text: "Our Classes"
        href: our-classes/index.qmd
      - text: "Student Resources"
        href: student-resources/index.qmd
      - text: "Events"
        href: events/index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "Gasshuku"
        href: gasshuku/index.qmd
      - text: "Calendar"
        href: calendar/index.qmd
      - text: "About"
        href: about/index.qmd

format:
  html:
    theme: [cosmo, assets/css/custom.scss]
    css: assets/css/styles.css
    toc: false
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;600;700&family=Lato:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    include-after-body: "_partials/footer.html"